# This file was generated by GoReleaser. DO NOT EDIT.
cask "myks" do
  desc "Configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "4.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "myks"
  depends_on formula: [
      "git",
      "helm",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v4.11.1/myks_4.11.1_darwin_amd64.tar.gz"
      sha256 "bed19b84d34b0447c72b8d42bbb12ef4ac06c4bda302708e51be1d96e29d1cfd"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v4.11.1/myks_4.11.1_darwin_arm64.tar.gz"
      sha256 "6b0399c45bdc50e37fe0065968337db70bb656c07378043c1b64b16c3c8809f4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v4.11.1/myks_4.11.1_linux_amd64.tar.gz"
      sha256 "fd885228c9e6a003ba8eea9b54a209661709555ef3673631da10fdd131cce80c"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v4.11.1/myks_4.11.1_linux_arm64.tar.gz"
      sha256 "1c1a58badc18d2b820f6ffe7ae53122538fc2390937e55c6b0925e046e001c2a"
    end
  end

  conflicts_with formula: [
      "myks",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/myks"]
    end
  end

  # No zap stanza required
end
