# This file was generated by GoReleaser. DO NOT EDIT.
cask "myks" do
  name "myks"
  desc "Configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "5.9.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "myks"
  depends_on formula: [
      "git",
      "helm",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v#{version}/myks_#{version}_darwin_amd64.tar.gz"
      sha256 "fb1995f851fa34727e61db19c427f232acab5c9fbcba12b0e3aa14a94cc44d1e"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v#{version}/myks_#{version}_darwin_arm64.tar.gz"
      sha256 "c989fea9733075b92956e4acbc9afc78ff5c1d34535bf869ddf446a6e68d76ac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v#{version}/myks_#{version}_linux_amd64.tar.gz"
      sha256 "fd7c4e092863155cd4398a10fd75721290290434e3868b7abdffd81be4688b4d"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v#{version}/myks_#{version}_linux_arm64.tar.gz"
      sha256 "d4ae1bbaa6f836ddcb9045d8f330e176b50755a1f9a6b6378abc4961ff1eeead"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/myks"]
    end
  end

  # No zap stanza required
end
