# This file was generated by GoReleaser. DO NOT EDIT.
cask "myks" do
  desc "Configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "4.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "myks"
  depends_on formula: [
      "git",
      "helm",
    ]

  on_macos do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v4.10.0/myks_4.10.0_darwin_amd64.tar.gz"
      sha256 "fcd65a2bfb4b3149291e4e63607d96720923344be61ac4521cf9fba01436edd0"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v4.10.0/myks_4.10.0_darwin_arm64.tar.gz"
      sha256 "3224408b2dd23d273f0fccd6b80f97b9188f427c26011c69c7885a8cd8540242"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v4.10.0/myks_4.10.0_linux_amd64.tar.gz"
      sha256 "67f4fe20fd2a6082cbb46562980f52dab4626e96596c99444527979ba2ea8339"
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v4.10.0/myks_4.10.0_linux_arm64.tar.gz"
      sha256 "7e34b5b5ebfa04e7a9143d03da4d44dcd598dec3413d4987a183a3f67ccb47f8"
    end
  end

  conflicts_with formula: [
      "myks",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/myks"]
    end
  end

  # No zap stanza required
end
