# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myks < Formula
  desc "Configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "4.4.0"
  license "MIT"

  depends_on "git" => :optional
  depends_on "helm" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mykso/myks/releases/download/v4.4.0/myks_4.4.0_darwin_amd64.tar.gz"
      sha256 "ef7cbc87397141a053f09d6887cbf751bd9fa864828ffe509b2f1c2e7686c73e"

      def install
        bin.install "myks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mykso/myks/releases/download/v4.4.0/myks_4.4.0_darwin_arm64.tar.gz"
      sha256 "2e17e824cb79fa76aae507edb84719ee8315b588cfef38dc8d6700cbb6607cb4"

      def install
        bin.install "myks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mykso/myks/releases/download/v4.4.0/myks_4.4.0_linux_amd64.tar.gz"
        sha256 "c22b126db3f45f7e67de8922836ae7106f1588be0d3edddc37989e3d0f3f610f"

        def install
          bin.install "myks"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mykso/myks/releases/download/v4.4.0/myks_4.4.0_linux_arm64.tar.gz"
        sha256 "58049c1fafadd12621378355616df5c8133de089d7d2c89fac24d96f48196bb9"

        def install
          bin.install "myks"
        end
      end
    end
  end
end
