# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myks < Formula
  desc "A configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "2.0.2"
  license "MIT"

  depends_on "git" => :optional
  depends_on "helm" => :optional
  depends_on "vendir" => :optional
  depends_on "ytt" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mykso/myks/releases/download/v2.0.2/myks_2.0.2_darwin_arm64.tar.gz"
      sha256 "bdea8b6509bb3927ea0db43d5aa342779992ba332f9a68bcc61cf274f50ce04e"

      def install
        bin.install "myks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mykso/myks/releases/download/v2.0.2/myks_2.0.2_darwin_amd64.tar.gz"
      sha256 "e05f6b37799db7fd622779f455f475da9b6de42109fb92cfe6e5d8d485720748"

      def install
        bin.install "myks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mykso/myks/releases/download/v2.0.2/myks_2.0.2_linux_arm64.tar.gz"
      sha256 "b89bafbfe8f998adf9793894c20dab1efefd673750ea702e3ffa6b337abc67fb"

      def install
        bin.install "myks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mykso/myks/releases/download/v2.0.2/myks_2.0.2_linux_amd64.tar.gz"
      sha256 "ba63603ff44fdd964a5f72861093f214cbefc71639871d2df705b4a63b7ed902"

      def install
        bin.install "myks"
      end
    end
  end
end
