# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Myks < Formula
  desc "Configuration framework for Kubernetes applications"
  homepage "https://github.com/mykso/myks"
  version "4.2.2"
  license "MIT"

  depends_on "git" => :optional
  depends_on "helm" => :optional

  on_macos do
    on_intel do
      url "https://github.com/mykso/myks/releases/download/v4.2.2/myks_4.2.2_darwin_amd64.tar.gz"
      sha256 "abc0dc0948881b0f5db6aa10acb4ef4c084d9ed480cd70709aac7bb2706818b6"

      def install
        bin.install "myks"
      end
    end
    on_arm do
      url "https://github.com/mykso/myks/releases/download/v4.2.2/myks_4.2.2_darwin_arm64.tar.gz"
      sha256 "b445df1683fd03352a1cf7e00b3a0548e9a62501e22886369f2988bfe4d8f4a5"

      def install
        bin.install "myks"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mykso/myks/releases/download/v4.2.2/myks_4.2.2_linux_amd64.tar.gz"
        sha256 "95384a63d9abb9861d6151398e453d809db287b7c85af81d8e9cf9fa2f5c9145"

        def install
          bin.install "myks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mykso/myks/releases/download/v4.2.2/myks_4.2.2_linux_arm64.tar.gz"
        sha256 "3212dc64536281eef675df6bb3368cc52e85167e6687ddbc322a85e63353fa72"

        def install
          bin.install "myks"
        end
      end
    end
  end
end
